# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b28be0c175a62f9b80f00d26a9b694521d211f2005a0f5afcb959f8e106253ca1e0ecabe770460ee022cfb610e2cf992225318a1465c2f0a1eff9bc46d4b3d2f

test:
  secret_key_base: 548049c48f34e84d1b9467595d3f79fe2b11a1524c2021003a7419b4d462d4913fbebf0e663f0fb81bc923e55d5713107b1bc084e632a5b6ab71cc53a26bedaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
